
#  ▄▄▄▄   ▄▄▄                
# █▀ ██  ██      █▄  █▄      
#    ██ ██    ▀▀▄██▄▄██▄     
#    █████    ██ ██  ██ ██ ██
#    ██ ██▄   ██ ██  ██ ██▄██
#  ▀██▀  ▀██▄▄██▄██ ▄██▄▄▀██▀
#                         ██ 
#                       ▀▀▀  

# Font
font_family      IosevkaTerm Nerd Font
font_size        14

# Terminal & Window
confirm_os_window_close 0
enable_audio_bell no
shell_integration no-cursor
scrollback_lines 2000
window_padding_width 14
background_opacity 0.98

# Cursor
cursor_shape block
cursor_blink_interval 0
cursor_trail 1

# Performance
input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

# Theme
include themes/koda-dark.conf
