set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set-window-option -g mode-keys vi

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'RyanMillerC/better-vim-tmux-resizer'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @minimal-tmux-indicator false
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-bg "magenta"

set -g pane-border-style "fg=colour240"
set -g pane-active-border-style "fg=magenta"

run '~/.tmux/plugins/tpm/tpm'
