#
#  ▄▄▄  ▄▄▄                                                
# █▀██  ██                                                 
#   ██  ██               ▄                            ▄    
#   ██████   ██ ██ ████▄ ████▄████▄ ▄▀▀█▄ ████▄ ▄█▀█▄ ████▄
#   ██  ██   ██▄██ ██ ██ ██   ██ ██ ▄█▀██ ██ ██ ██▄█▀ ██   
# ▀██▀  ▀██▄▄▄▀██▀▄████▀▄█▀  ▄████▀▄▀█▄██▄████▀▄▀█▄▄▄▄█▀   
#              ██  ██         ██          ██               
#            ▀▀▀   ▀          ▀           ▀                

wallpaper {
    monitor = DP-1
    path = /home/florian/Pictures/Wallpapers/marble.png
    fit_mode = cover
}

splash = false
